/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a normal local install.
// It is committed here so TypeScript checks can run immediately in the repository skeleton.
